version: '3.5'

services:
  frontend:
    build: .
    image: vue-music
    container_name: frontend
    ports: 
      - 8080:8080
    networks:
      - frontend

networks:
  frontend:
    name: frontend_network
